---
version: "3"
services:
#  sabredav:
#    image: php:8.1-alpine3.15
#    restart: always
#    volumes:
#      - ./:/var/www/html/
#    ports:
#      - "4040:4040"
#    command: php -S 0.0.0.0:4040 /var/www/html/src/WebDAV/resources/server.php
#  webdav:
#    image: bytemark/webdav
#    restart: always
#    ports:
#      - "4080:80"
#    environment:
#      AUTH_TYPE: Digest
#      USERNAME: alice
#      PASSWORD: secret1234
#      ANONYMOUS_METHODS: 'GET,OPTIONS'
  sftp:
    container_name: sftp
    restart: always
    image: atmoz/sftp:alpine
    volumes:
      - ./docker/sftp/users.conf:/etc/sftp/users.conf
      - ./docker/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./docker/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./docker/sftp/id_rsa.pub:/home/bar/.ssh/keys/id_rsa.pub
    ports:
      - "2222:22"
  sftp_eddsa_only:
    container_name: sftp_eddsa_only
    restart: always
    image: atmoz/sftp:alpine
    volumes:
      - ./docker/sftp/users.conf:/etc/sftp/users.conf
      - ./docker/sftp/sshd_custom_configs.sh:/etc/sftp.d/sshd_custom_configs.sh
      - ./docker/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
    ports:
      - "2223:22"
#  ftp:
#    container_name: ftp
#    restart: always
#    image: delfer/alpine-ftp-server
#    environment:
#      USERS: 'foo|pass|/home/foo/upload'
#      ADDRESS: 'localhost'
#    ports:
#      - "2121:21"
#      - "21000-21010:21000-21010"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    profiles: ["azure"]
    restart: unless-stopped
    healthcheck:
      test:
        wget --no-verbose --tries=1 --spider http://localhost:10000/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
