name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    paths:
      - package.json
      - package-lock.json
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-dependabot-pr:
    name: Merge dependabot PR
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge PR
        if: ${{ steps.meta.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
