name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: read # Required for change detection

env:
  ECR_REPOSITORY: 'duna-staging'
  APP_BASE_IMAGE: 'ghcr.io/building-duna/duna-application/duna-node:base-20.9.0'
  CI_BASE_IMAGE: 'ghcr.io/building-duna/duna-application/duna-node:ci-20.9.0'
  IMAGE_TAG: "prod-1.${{ github.run_id }}"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    name: Install dependencies
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: ./.github/actions/install-dependencies
        name: Install NPM dependencies
        with:
          cache-key: npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          cache-restore-keys: npm-caches-${{ matrix.node }}
      - name: Run tests
        run: npm run test
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"

